# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 20:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Titre')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='titre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix')),
                ('barcode', models.CharField(help_text='Code EAN13 (13 chiffres)', max_length=13, validators=[django.core.validators.RegexValidator('[0-9]{13}')], verbose_name='code-barres')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date de création')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='coupons.Category')),
            ],
        ),
    ]
