# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('price', 'title'), 'verbose_name': 'coupon', 'verbose_name_plural': 'coupons'},
        ),
    ]
