# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20170408_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=80, verbose_name='titre'),
        ),
    ]
