# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20170408_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.CharField(help_text="ID du lieu selon l'API de Google Maps", max_length=50, primary_key=True, serialize=False, verbose_name='place id')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('address', models.CharField(max_length=150, verbose_name='adresse')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'ordering': ('name', 'address'),
            },
        ),
    ]
