# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='créé le')),
                ('author_ip', models.GenericIPAddressField(unpack_ipv4=True, verbose_name="addresse IP de l'auteur")),
                ('does_coupon_work', models.BooleanField(default=True, verbose_name='le coupon marche-t-il')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coupons.Coupon')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='coupons.Restaurant')),
            ],
        ),
    ]
