# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'commentaire', 'verbose_name_plural': 'commentaires'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('address',), 'verbose_name': 'restaurant', 'verbose_name_plural': 'restaurants'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Masque le coupon pour les utilisateurs anonymes', verbose_name='désactivé'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='does_coupon_work',
            field=models.BooleanField(default=True, verbose_name='le coupon marche-t-il ?'),
        ),
    ]
