# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 18:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_auto_20170718_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='barcode',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('[0-9]+')], verbose_name='code-barres'),
        ),
    ]
