# Generated by Django 2.0 on 2018-08-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_auto_20170917_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='featured',
            field=models.BooleanField(default=False, help_text='Apparaît dans les bons du moments', verbose_name='bon du moment'),
        ),
    ]
