# Generated by Django 2.0 on 2018-08-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_coupon_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='featured',
            field=models.BooleanField(default=True, help_text='Apparaît dans les bons du moments', verbose_name='bon du moment'),
        ),
    ]
